# Generated by Django 2.0.2 on 2018-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q', '0002_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message',
            field=models.TextField(default='message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='message'),
        ),
    ]
