# Generated by Django 2.0.2 on 2018-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.RemoveField(
            model_name='board',
            name='genre',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='board',
            name='genre',
            field=models.ManyToManyField(blank=True, to='board.Genre'),
        ),
    ]
