# Generated by Django 2.0.2 on 2018-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180226_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='genre',
            field=models.ManyToManyField(to='board.Genre'),
        ),
    ]
