# Generated by Django 2.0.2 on 2018-03-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180301_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
