# Generated by Django 2.0.2 on 2018-03-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='desc', max_length=150),
        ),
    ]
