# Generated by Django 2.0.2 on 2018-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
