# Generated by Django 2.0.2 on 2018-03-02 05:31
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

def slugify_title(apps, schema_editor):
    Topic = apps.get_model('board', 'Topic')
    for topic in Topic.objects.all():
        topic.slug = slugify(topic.title)
        topic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_topic_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_title),
    ]
