# Generated by Django 2.0.2 on 2018-03-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20180304_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='starter',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
